datadf <- as.data.frame(data)
datadf$year <- as.factor(substr(datadf$pickup_datetime,1,4))
datadf$yearnum <- as.numeric(datadf$year)
str(datadf)
summary(datadf)
boxplot(datadf$fare_amount~datadf$year, range=0)
boxplot(datadf$fare_amount~datadf$passenger_count, range=0)
plot(datadf$year, datadf$fare_amount)
plot(datadf$passenger_count,datadf$fare_amount)
lm_fare_count <- lm(fare_amount~passenger_count,data=datadf)
summary(lm_fare_count)
lm_fare_year <- lm(fare_amount~year,data=datadf)
summary(lm_fare_year)
library(Imap)
datadf$dist <- gdist(lat.1=datadf$pickup_latitude, lon.1=datadf$pickup_longitude, lat.2=datadf$dropoff_latitude, lon.2=datadf$dropoff_longitude, units="miles")
subset(datadf, dist >= 15)
plot(datadf$dist, datadf$fare_amount)
#manually remove some outliers to get a better regression fit
datadf_trim <- subset(datadf, dist <= 15)
datadf_trim <- subset(datadf_trim, pickup_longitude >= -74.025)
datadf_trim <- subset(datadf_trim, dropoff_longitude >= -74.025)
plot(datadf_trim$dist, datadf_trim$fare_amount)
#base regression fare and distance
lm_fare_dist <- lm(fare_amount~dist, data=datadf_trim)
summary(lm_fare_dist)
#regression including interaction with fare*year with year as a factor
lm_fare_distyear <- lm(fare_amount~dist*year, data=datadf_trim)
summary(lm_fare_distyear)
#regression including interaction with fare*year with year as a numeric from 1 to 7
lm_fare_distyearnum <- lm(fare_amount~dist*yearnum, data=datadf_trim)
summary(lm_fare_distyearnum)
